### PR TITLE
Use 5.x.x version of koa-views

### PR DESCRIPTION
**Pull request by kuritkaj**

### CODE REVIEW

**Comment by machined** [comment]
@kuritkaj is there a reason why the npm-shrinkwrap.json is not updated?

**Comment by kuritkaj** [comment]
@machined I completely forgotten that we are using it. But the fix is no more necessary I think.

**Comment by machined** [comment]
Ok, but why isn't the fix no longer necessary? I (still) get the following error when trying to npm install from inside the example_app:

[example_app (master)]$ npm install
npm WARN package.json 7pass-nodejs-sdk-example-app@0.0.1 No repository field.
npm WARN package.json 7pass-nodejs-sdk-example-app@0.0.1 No README data
npm WARN package.json 7pass-nodejs-sdk-example-app@0.0.1 No license field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/phil/.nvm/versions/node/v4.4.4/bin/node" "/Users/phil/.nvm/versions/node/v4.4.4/bin/npm" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code E404

npm ERR! 404 no such package available : @f/defaults
npm ERR! 404 
npm ERR! 404 '@f/defaults' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'koa-views'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by machined** [comment]
My bad. We don't use shrinkwrap for the example_app.

**Pull request merged**
